// Mocks generated by Mockito 5.0.16 from annotations
// in tv_shows/test/presentation/provider/tv_show_detail_notifier_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:core_app/src/common/failure.dart' as _i6;
import 'package:core_app/src/domain/entities/tv_show.dart' as _i9;
import 'package:core_app/src/domain/entities/tv_show_detail.dart' as _i7;
import 'package:core_app/src/domain/repositories/tv_show_repository.dart'
    as _i2;
import 'package:core_app/src/domain/usecases/tv_show/get_tv_show_detail.dart'
    as _i4;
import 'package:core_app/src/domain/usecases/tv_show/get_tv_show_recommendations.dart'
    as _i8;
import 'package:core_app/src/domain/usecases/tv_show/get_watchlist_status_tv_show.dart'
    as _i10;
import 'package:core_app/src/domain/usecases/tv_show/remove_watchlist_tv_show.dart'
    as _i12;
import 'package:core_app/src/domain/usecases/tv_show/save_watchlist_tv_show.dart'
    as _i11;
import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTVShowRepository_0 extends _i1.Fake implements _i2.TVShowRepository {
}

class _FakeEither_1<L, R> extends _i1.Fake implements _i3.Either<L, R> {}

/// A class which mocks [GetTVShowDetail].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVShowDetail extends _i1.Mock implements _i4.GetTVShowDetail {
  MockGetTVShowDetail() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, _i7.TVShowDetail>> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i3.Either<_i6.Failure, _i7.TVShowDetail>>.value(
              _FakeEither_1<_i6.Failure, _i7.TVShowDetail>())) as _i5
          .Future<_i3.Either<_i6.Failure, _i7.TVShowDetail>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetTVShowRecommendations].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTVShowRecommendations extends _i1.Mock
    implements _i8.GetTVShowRecommendations {
  MockGetTVShowRecommendations() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i9.TVShow>>> execute(dynamic id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<_i3.Either<_i6.Failure, List<_i9.TVShow>>>.value(
              _FakeEither_1<_i6.Failure, List<_i9.TVShow>>())) as _i5
          .Future<_i3.Either<_i6.Failure, List<_i9.TVShow>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [GetWatchListStatusTVShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWatchListStatusTVShow extends _i1.Mock
    implements _i10.GetWatchListStatusTVShow {
  MockGetWatchListStatusTVShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);
  @override
  _i5.Future<bool> execute(int? id) =>
      (super.noSuchMethod(Invocation.method(#execute, [id]),
          returnValue: Future<bool>.value(false)) as _i5.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [SaveWatchlistTVShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveWatchlistTVShow extends _i1.Mock
    implements _i11.SaveWatchlistTVShow {
  MockSaveWatchlistTVShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TVShowDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [RemoveWatchlistTVShow].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveWatchlistTVShow extends _i1.Mock
    implements _i12.RemoveWatchlistTVShow {
  MockRemoveWatchlistTVShow() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TVShowRepository get repository =>
      (super.noSuchMethod(Invocation.getter(#repository),
          returnValue: _FakeTVShowRepository_0()) as _i2.TVShowRepository);
  @override
  _i5.Future<_i3.Either<_i6.Failure, String>> execute(
          _i7.TVShowDetail? movie) =>
      (super.noSuchMethod(Invocation.method(#execute, [movie]),
              returnValue: Future<_i3.Either<_i6.Failure, String>>.value(
                  _FakeEither_1<_i6.Failure, String>()))
          as _i5.Future<_i3.Either<_i6.Failure, String>>);
  @override
  String toString() => super.toString();
}
